### ISSUE TITLE
calendar GestureDetector Enhancement

### ISSUE THREAD

**Issue by gohdong** [gohdong/widgetable_calendar#10]
제스쳐디텍터가 너무 조잡함 개선이 필요함
==========Translate==========
GestureDetector tooooo poorly need to Improved

**Comment by ToasT1ng** [comment]
I'll do it

**Comment by ToasT1ng** [comment]
I've improved it.

All source codes are in "gesture" Branch. 
https://github.com/ToasT1ng/widgetable_calendar/commits/gesture

If you accept Pull Requests first, then I will make another Pull Requests.
