### ISSUE TITLE
need a page where we can register our schedule.

### ISSUE THREAD

**Issue by ToasT1ng** [gohdong/widgetable_calendar#16]
일정을 등록할 수 있는 페이지를 만들어야합니다. (당장은 데이터베이스 X)

==========Translate==========

We must create a page where we can register our schedule. (Without database!)

**Comment by gohdong** [comment]
Didn't we decide to do that on second objective?

**Comment by gohdong** [comment]
I'll do that

**Comment by gohdong** [comment]
@ToasT1ng 
On second thought, we just need to create addEvent methods on the controller. 
The page that you mentioned can be added to the example code.
I'll make addEvent method
