### ISSUE TITLE
make calendar basic layout

### ISSUE THREAD

**Issue by gohdong** [gohdong/widgetable_calendar#2]
달력을 나타낼 수 있는 기본 레이아웃이 필요합니다.

===========Translate===========

A basic layout is required to represent the calendar.

**Comment by ToasT1ng** [comment]
I'll make a simple calendar to check today's date.
( It can't check the previous month or next month. )

+++ I can't assign myself because i'm not a contributor to this repo. PLZ assign me.

**Comment by gohdong** [comment]
> I'll

Ok~

**Comment by gohdong** [comment]
@ToasT1ng Ok~

**Comment by gohdong** [comment]
I will make basic layout

**Comment by ToasT1ng** [comment]
@gohdong NO.. I did
<img width="405" alt="스크린샷 2020-10-13 오후 4 45 00" src="https://user-images.githubusercontent.com/26130631/95831573-2bf86a80-0d74-11eb-8ab3-c75e30628841.png">

**Comment by ToasT1ng** [comment]
I made simple calendar. It can check the previous month or next month. 

BUT I didn't think about CONTROLLER...

All source codes are in "simpleCalendar" Branch

https://github.com/ToasT1ng/widgetable_calendar/tree/simpleCalendar

**Comment by gohdong** [comment]
@ToasT1ng ㅠ
