### ISSUE TITLE
manufacture events&holidays format

### ISSUE THREAD

**Issue by wangjh789** [gohdong/widgetable_calendar#20]
이벤트, 공휴일 자료형 다듬어야 됩니다.

==========Translate ==========

we should make process manufacturing List<Map<DateTime,String>> to Map<DateTime,List>

**Comment by ToasT1ng** [comment]
Why? Didn't we decide to use **List<Map<DateTime,String>>** data type at the meeting yesterday?

**Comment by ToasT1ng** [comment]
Check this issue - #38
