### ISSUE TITLE
select day bug

### ISSUE THREAD

**Issue by gohdong** [gohdong/widgetable_calendar#27]
![스크린샷 2020-10-18 오전 1 11 47](https://user-images.githubusercontent.com/22044475/96355983-6458c980-1123-11eb-9ff8-a9637a008474.png)
0일 선택시 모두 선택 됨

==========Translate==========

All selected on 0 day selection

**Comment by ToasT1ng** [comment]
I'll fix it

**Comment by ToasT1ng** [comment]
Check this COMMIT. ( on Stream Branch )

https://github.com/gohdong/widgetable_calendar/commit/a3e6ab863ba75304a059cbd36b17cff3816319ca

**Comment by ToasT1ng** [comment]
Resolved in: #32
