### ISSUE TITLE
Label deletion function

### ISSUE THREAD

**Issue by ToasT1ng** [gohdong/widgetable_calendar#44]
특정 라벨을 삭제할 때, 그 라벨을 갖는 모든 이벤트를 삭제하는게 맞겠쥬? ( 초록색 라벨을 삭제하면 초록색 라벨로 표시된 모든 이벤트를 삭제 )    

만약 그렇다면, Map<DateTime,List> **eventsByDate** , Map<String,Map> **eachEvent** 둘 다 에서 해당하는거 찾아서 삭제할게요?   
 
아니면 안전하게 이벤트 맵에 delete or not 필드를 새로 만들어서 할까요?

==========Translate==========

When we delete a label, we should delete all events of that label, right? ( If you delete the green label, all events marked with the green label are deleted )    

If so, will I find the corresponding one in Map<DateTime,List> **eventsByDate** and Map<String,Map> **eachEvent** and delete it?    

Or maybe just create a new **delete or not** field to be safe?

**Comment by ToasT1ng** [comment]
labelEnhance branch <- Just delete the contents of the map https://github.com/gohdong/widgetable_calendar/commit/741829fdd9c70873b2774fc86128efc144caa6e0
labelDeletion branch <- Use delete or not field ( deletion field ) https://github.com/gohdong/widgetable_calendar/commit/fdbe7f3316393c144bf6c1953abea028326912c0

**Comment by gohdong** [comment]
Just delete the contents of the map would be better.

**Comment by ToasT1ng** [comment]
Ok ~
